//load dojo RPC
dojo.require("dojo.rpc.*");

function addItemToForm(attributeControl) {
    try{
        var tr = new Element('tr');
        tr.insert( new Element('td', { 'width': '20%' }).update(attributeControl.controlName + ':') );
        
        var td;
        if( attributeControl.controlType == 'select'){
            var select = new Element(attributeControl.controlType);
            attributeControl.values.each(function(value){
                select.insert(new Element('option', { 'value':value } ).update(value) );
            });
            td = select.wrap('td');
        }else td = new Element(attributeControl.controlType);
        tr.insert( new Element('td', { 'width': '30%' } ).update(td) );
        

        $('human_attr_tab').down('tbody').insert(tr);
    } catch(e) { console.log(e); }
}

function callService(){
    // create service object(proxy) using SMD (generated by the json result)
    // serviceURL defined in the master.jsp
    var service = new dojo.rpc.JsonService(serviceURL);

    var defered = service.getAttributeControl("Decision_Of_Owner");
    defered.addCallback(addItemToForm);
}

/*
    //function called when remote method returns
    var callback = function(bean) {
        alert("Price for " + bean.type + " is " + bean.price);
    };

    //parameter
    var bean = {type: "Mocca"};

    /*
    //execute remote method
    var defered = service.doSomething(bean, 5);

    //attach callback to defered object
    defered.addCallback(callback);
    */