/*
 *  Javascript class that interacts with the RPC Methods available
 */

var CIKPWebService = Class.create({
    initialize: function(serviceURL) {
        //load dojo RPC
        dojo.require("dojo.rpc.*");
        // create service object(proxy) using SMD (generated by the json result)
        // serviceURL defined in the master.jsp
        this.service = new dojo.rpc.JsonService(serviceURL);
    },
    getAttributeControl: function(attributeName, callbackFunction) {
        var defered = this.service.getAttributeControl(attributeName);
        defered.addCallback(callbackFunction);
    }
});
var service = new CIKPWebService(serviceURL);