package org.fct.unl.pt.cikp.data.portal;
// Generated 26/Mar/2009 22:39:19 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * File generated by hbm2java
 */
@Entity
@Table(name="file"
    ,catalog="cikp"
)
public class File  implements java.io.Serializable {


     private Integer fileId;
     private byte[] file;
     private Set<KnowledgeItem> knowledgeItems = new HashSet<KnowledgeItem>(0);

    public File() {
    }

	
    public File(byte[] file) {
        this.file = file;
    }
    public File(byte[] file, Set<KnowledgeItem> knowledgeItems) {
       this.file = file;
       this.knowledgeItems = knowledgeItems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="File_ID", unique=true, nullable=false)
    public Integer getFileId() {
        return this.fileId;
    }
    
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }
    
    @Column(name="File", nullable=false)
    public byte[] getFile() {
        return this.file;
    }
    
    public void setFile(byte[] file) {
        this.file = file;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="file")
    public Set<KnowledgeItem> getKnowledgeItems() {
        return this.knowledgeItems;
    }
    
    public void setKnowledgeItems(Set<KnowledgeItem> knowledgeItems) {
        this.knowledgeItems = knowledgeItems;
    }




}


