package org.fct.unl.pt.cikp.data.portal;
// Generated 26/Mar/2009 22:39:19 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Keyword generated by hbm2java
 */
@Entity
@Table(name="keyword"
    ,catalog="cikp"
)
public class Keyword  implements java.io.Serializable {


     private Integer keywordId;
     private String keyword;
     private Set<KnowledgeItem> knowledgeItems = new HashSet<KnowledgeItem>(0);

    public Keyword() {
    }

	
    public Keyword(String keyword) {
        this.keyword = keyword;
    }
    public Keyword(String keyword, Set<KnowledgeItem> knowledgeItems) {
       this.keyword = keyword;
       this.knowledgeItems = knowledgeItems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Keyword_ID", unique=true, nullable=false)
    public Integer getKeywordId() {
        return this.keywordId;
    }
    
    public void setKeywordId(Integer keywordId) {
        this.keywordId = keywordId;
    }
    
    @Column(name="Keyword", nullable=false, length=100)
    public String getKeyword() {
        return this.keyword;
    }
    
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="keywords")
    public Set<KnowledgeItem> getKnowledgeItems() {
        return this.knowledgeItems;
    }
    
    public void setKnowledgeItems(Set<KnowledgeItem> knowledgeItems) {
        this.knowledgeItems = knowledgeItems;
    }




}


