package org.fct.unl.pt.cikp.data.portal;
// Generated 1/Abr/2009 0:12:44 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OntologyControlsPortal generated by hbm2java
 */
@Entity
@Table(name="ontology_controls_portal"
    ,catalog="cikp"
)
public class OntologyControlsPortal  implements java.io.Serializable {


     private Integer ontologyControlsId;
     private String controlType;
     private String controlId;
     private String propertyName;

    public OntologyControlsPortal() {
    }

    public OntologyControlsPortal(String controlType, String controlId, String propertyName) {
       this.controlType = controlType;
       this.controlId = controlId;
       this.propertyName = propertyName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Ontology_Controls_ID", unique=true, nullable=false)
    public Integer getOntologyControlsId() {
        return this.ontologyControlsId;
    }
    
    public void setOntologyControlsId(Integer ontologyControlsId) {
        this.ontologyControlsId = ontologyControlsId;
    }
    
    @Column(name="Control_Type", nullable=false, length=45)
    public String getControlType() {
        return this.controlType;
    }
    
    public void setControlType(String controlType) {
        this.controlType = controlType;
    }
    
    @Column(name="Control_Id", nullable=false, length=100)
    public String getControlId() {
        return this.controlId;
    }
    
    public void setControlId(String controlId) {
        this.controlId = controlId;
    }
    
    @Column(name="Property_Name", nullable=false, length=100)
    public String getPropertyName() {
        return this.propertyName;
    }
    
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }




}


