package org.fct.unl.pt.cikp.data.portal;
// Generated 1/Abr/2009 0:12:44 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubscriptionPortal generated by hbm2java
 */
@Entity
@Table(name="subscription_portal"
    ,catalog="cikp"
)
public class SubscriptionPortal  implements java.io.Serializable {


     private Integer subscriptionId;
     private UserPortal userPortal;
     private String knowledge_item_file_name;
     private Integer knowledge_item_file_size;
     private Date knowledge_item_creation_time;
     private Date knowledge_item_creation_date;
     private String knowledge_item_author;
     private String knowledge_item_composition_language;
     private String knowledge_item_copyright_owner;
     private String knowledge_item_destination;
     private String knowledge_item_file_type;
     private String knowledge_item_security_clearance;
     private String knowledge_item_source;
     private String knowledge_item_type;
     private String subject_domain;
     private Set<KnowledgeItemPortal> knowledgeItemPortals = new HashSet<KnowledgeItemPortal>(0);
     private Set<KeywordPortal> keywordPortals = new HashSet<KeywordPortal>(0);

    public SubscriptionPortal() {
    }

	
    public SubscriptionPortal(UserPortal userPortal) {
        this.userPortal = userPortal;
    }
    public SubscriptionPortal(UserPortal userPortal, String knowledgeItemFileName, Integer knowledgeItemFileSize, Date knowledgeItemCreationTime, Date knowledgeItemCreationDate, String knowledgeItemAuthor, String knowledgeItemCompositionLanguage, String knowledgeItemCopyrightOwner, String knowledgeItemDestination, String knowledgeItemFileType, String knowledgeItemSecurityClearance, String knowledgeItemSource, String knowledgeItemType, String subjectDomain, Set<KnowledgeItemPortal> knowledgeItemPortals, Set<KeywordPortal> keywordPortals) {
       this.userPortal = userPortal;
       this.knowledge_item_file_name = knowledgeItemFileName;
       this.knowledge_item_file_size = knowledgeItemFileSize;
       this.knowledge_item_creation_time = knowledgeItemCreationTime;
       this.knowledge_item_creation_date = knowledgeItemCreationDate;
       this.knowledge_item_author = knowledgeItemAuthor;
       this.knowledge_item_composition_language = knowledgeItemCompositionLanguage;
       this.knowledge_item_copyright_owner = knowledgeItemCopyrightOwner;
       this.knowledge_item_destination = knowledgeItemDestination;
       this.knowledge_item_file_type = knowledgeItemFileType;
       this.knowledge_item_security_clearance = knowledgeItemSecurityClearance;
       this.knowledge_item_source = knowledgeItemSource;
       this.knowledge_item_type = knowledgeItemType;
       this.subject_domain = subjectDomain;
       this.knowledgeItemPortals = knowledgeItemPortals;
       this.keywordPortals = keywordPortals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Subscription_ID", unique=true, nullable=false)
    public Integer getSubscriptionId() {
        return this.subscriptionId;
    }
    
    public void setSubscriptionId(Integer subscriptionId) {
        this.subscriptionId = subscriptionId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public UserPortal getUserPortal() {
        return this.userPortal;
    }
    
    public void setUserPortal(UserPortal userPortal) {
        this.userPortal = userPortal;
    }
    
    @Column(name="Knowledge_Item_File_Name", length=20)
    public String getKnowledge_item_file_name() {
        return this.knowledge_item_file_name;
    }
    
    public void setKnowledge_item_file_name(String knowledgeItemFileName) {
        this.knowledge_item_file_name = knowledgeItemFileName;
    }
    
    @Column(name="Knowledge_Item_File_Size")
    public Integer getKnowledge_item_file_size() {
        return this.knowledge_item_file_size;
    }
    
    public void setKnowledge_item_file_size(Integer knowledgeItemFileSize) {
        this.knowledge_item_file_size = knowledgeItemFileSize;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="Knowledge_Item_Creation_Time", length=8)
    public Date getKnowledge_item_creation_time() {
        return this.knowledge_item_creation_time;
    }
    
    public void setKnowledge_item_creation_time(Date knowledgeItemCreationTime) {
        this.knowledge_item_creation_time = knowledgeItemCreationTime;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="Knowledge_Item_Creation_Date", length=10)
    public Date getKnowledge_item_creation_date() {
        return this.knowledge_item_creation_date;
    }
    
    public void setKnowledge_item_creation_date(Date knowledgeItemCreationDate) {
        this.knowledge_item_creation_date = knowledgeItemCreationDate;
    }
    
    @Column(name="Knowledge_Item_Author", length=200)
    public String getKnowledge_item_author() {
        return this.knowledge_item_author;
    }
    
    public void setKnowledge_item_author(String knowledgeItemAuthor) {
        this.knowledge_item_author = knowledgeItemAuthor;
    }
    
    @Column(name="Knowledge_Item_Composition_Language", length=100)
    public String getKnowledge_item_composition_language() {
        return this.knowledge_item_composition_language;
    }
    
    public void setKnowledge_item_composition_language(String knowledgeItemCompositionLanguage) {
        this.knowledge_item_composition_language = knowledgeItemCompositionLanguage;
    }
    
    @Column(name="Knowledge_Item_Copyright_Owner", length=200)
    public String getKnowledge_item_copyright_owner() {
        return this.knowledge_item_copyright_owner;
    }
    
    public void setKnowledge_item_copyright_owner(String knowledgeItemCopyrightOwner) {
        this.knowledge_item_copyright_owner = knowledgeItemCopyrightOwner;
    }
    
    @Column(name="Knowledge_Item_Destination", length=100)
    public String getKnowledge_item_destination() {
        return this.knowledge_item_destination;
    }
    
    public void setKnowledge_item_destination(String knowledgeItemDestination) {
        this.knowledge_item_destination = knowledgeItemDestination;
    }
    
    @Column(name="Knowledge_Item_File_Type", length=50)
    public String getKnowledge_item_file_type() {
        return this.knowledge_item_file_type;
    }
    
    public void setKnowledge_item_file_type(String knowledgeItemFileType) {
        this.knowledge_item_file_type = knowledgeItemFileType;
    }
    
    @Column(name="Knowledge_Item_Security_Clearance", length=100)
    public String getKnowledge_item_security_clearance() {
        return this.knowledge_item_security_clearance;
    }
    
    public void setKnowledge_item_security_clearance(String knowledgeItemSecurityClearance) {
        this.knowledge_item_security_clearance = knowledgeItemSecurityClearance;
    }
    
    @Column(name="Knowledge_Item_Source", length=20)
    public String getKnowledge_item_source() {
        return this.knowledge_item_source;
    }
    
    public void setKnowledge_item_source(String knowledgeItemSource) {
        this.knowledge_item_source = knowledgeItemSource;
    }
    
    @Column(name="Knowledge_Item_Type", length=100)
    public String getKnowledge_item_type() {
        return this.knowledge_item_type;
    }
    
    public void setKnowledge_item_type(String knowledgeItemType) {
        this.knowledge_item_type = knowledgeItemType;
    }
    
    @Column(name="Subject_Domain", length=100)
    public String getSubject_domain() {
        return this.subject_domain;
    }
    
    public void setSubject_domain(String subjectDomain) {
        this.subject_domain = subjectDomain;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="subscriptionPortals")
    public Set<KnowledgeItemPortal> getKnowledgeItemPortals() {
        return this.knowledgeItemPortals;
    }
    
    public void setKnowledgeItemPortals(Set<KnowledgeItemPortal> knowledgeItemPortals) {
        this.knowledgeItemPortals = knowledgeItemPortals;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="subscription_keyword_portal", catalog="cikp", joinColumns = { 
        @JoinColumn(name="Subscription_ID", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Keyword_ID", nullable=false, updatable=false) })
    public Set<KeywordPortal> getKeywordPortals() {
        return this.keywordPortals;
    }
    
    public void setKeywordPortals(Set<KeywordPortal> keywordPortals) {
        this.keywordPortals = keywordPortals;
    }




}


