package org.fct.unl.pt.cikp.data.portal;
// Generated 26/Mar/2009 23:51:03 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubscriptionPortal generated by hbm2java
 */
@Entity
@Table(name="subscription_portal"
    ,catalog="cikp"
)
public class SubscriptionPortal  implements java.io.Serializable {


     private Integer subscriptionId;
     private UserPortal userPortal;
     private String name;
     private Integer knowledgeItemFileSize;
     private Date knowledgeItemCreationTime;
     private Date knowledgeItemCreationDate;
     private String knowledgeItemAuthor;
     private String knowledgeItemCompositionLanguage;
     private String knowledgeItemCopyrightOwner;
     private String knowledgeItemDestination;
     private String knowledgeItemFileType;
     private String knowledgeItemSecurityClearance;
     private String knowledgeItemSource;
     private String knowledgeItemType;
     private String subjectDomain;

    public SubscriptionPortal() {
    }

	
    public SubscriptionPortal(UserPortal userPortal) {
        this.userPortal = userPortal;
    }
    public SubscriptionPortal(UserPortal userPortal, String name, Integer knowledgeItemFileSize, Date knowledgeItemCreationTime, Date knowledgeItemCreationDate, String knowledgeItemAuthor, String knowledgeItemCompositionLanguage, String knowledgeItemCopyrightOwner, String knowledgeItemDestination, String knowledgeItemFileType, String knowledgeItemSecurityClearance, String knowledgeItemSource, String knowledgeItemType, String subjectDomain) {
       this.userPortal = userPortal;
       this.name = name;
       this.knowledgeItemFileSize = knowledgeItemFileSize;
       this.knowledgeItemCreationTime = knowledgeItemCreationTime;
       this.knowledgeItemCreationDate = knowledgeItemCreationDate;
       this.knowledgeItemAuthor = knowledgeItemAuthor;
       this.knowledgeItemCompositionLanguage = knowledgeItemCompositionLanguage;
       this.knowledgeItemCopyrightOwner = knowledgeItemCopyrightOwner;
       this.knowledgeItemDestination = knowledgeItemDestination;
       this.knowledgeItemFileType = knowledgeItemFileType;
       this.knowledgeItemSecurityClearance = knowledgeItemSecurityClearance;
       this.knowledgeItemSource = knowledgeItemSource;
       this.knowledgeItemType = knowledgeItemType;
       this.subjectDomain = subjectDomain;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Subscription_ID", unique=true, nullable=false)
    public Integer getSubscriptionId() {
        return this.subscriptionId;
    }
    
    public void setSubscriptionId(Integer subscriptionId) {
        this.subscriptionId = subscriptionId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public UserPortal getUserPortal() {
        return this.userPortal;
    }
    
    public void setUserPortal(UserPortal userPortal) {
        this.userPortal = userPortal;
    }
    
    @Column(name="Name", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="Knowledge_Item_File_Size")
    public Integer getKnowledgeItemFileSize() {
        return this.knowledgeItemFileSize;
    }
    
    public void setKnowledgeItemFileSize(Integer knowledgeItemFileSize) {
        this.knowledgeItemFileSize = knowledgeItemFileSize;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="Knowledge_Item_Creation_Time", length=8)
    public Date getKnowledgeItemCreationTime() {
        return this.knowledgeItemCreationTime;
    }
    
    public void setKnowledgeItemCreationTime(Date knowledgeItemCreationTime) {
        this.knowledgeItemCreationTime = knowledgeItemCreationTime;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="Knowledge_Item_Creation_Date", length=10)
    public Date getKnowledgeItemCreationDate() {
        return this.knowledgeItemCreationDate;
    }
    
    public void setKnowledgeItemCreationDate(Date knowledgeItemCreationDate) {
        this.knowledgeItemCreationDate = knowledgeItemCreationDate;
    }
    
    @Column(name="Knowledge_Item_Author", length=200)
    public String getKnowledgeItemAuthor() {
        return this.knowledgeItemAuthor;
    }
    
    public void setKnowledgeItemAuthor(String knowledgeItemAuthor) {
        this.knowledgeItemAuthor = knowledgeItemAuthor;
    }
    
    @Column(name="Knowledge_Item_Composition_Language", length=100)
    public String getKnowledgeItemCompositionLanguage() {
        return this.knowledgeItemCompositionLanguage;
    }
    
    public void setKnowledgeItemCompositionLanguage(String knowledgeItemCompositionLanguage) {
        this.knowledgeItemCompositionLanguage = knowledgeItemCompositionLanguage;
    }
    
    @Column(name="Knowledge_Item_Copyright_Owner", length=200)
    public String getKnowledgeItemCopyrightOwner() {
        return this.knowledgeItemCopyrightOwner;
    }
    
    public void setKnowledgeItemCopyrightOwner(String knowledgeItemCopyrightOwner) {
        this.knowledgeItemCopyrightOwner = knowledgeItemCopyrightOwner;
    }
    
    @Column(name="Knowledge_Item_Destination", length=100)
    public String getKnowledgeItemDestination() {
        return this.knowledgeItemDestination;
    }
    
    public void setKnowledgeItemDestination(String knowledgeItemDestination) {
        this.knowledgeItemDestination = knowledgeItemDestination;
    }
    
    @Column(name="Knowledge_Item_File_Type", length=50)
    public String getKnowledgeItemFileType() {
        return this.knowledgeItemFileType;
    }
    
    public void setKnowledgeItemFileType(String knowledgeItemFileType) {
        this.knowledgeItemFileType = knowledgeItemFileType;
    }
    
    @Column(name="Knowledge_Item_Security_Clearance", length=100)
    public String getKnowledgeItemSecurityClearance() {
        return this.knowledgeItemSecurityClearance;
    }
    
    public void setKnowledgeItemSecurityClearance(String knowledgeItemSecurityClearance) {
        this.knowledgeItemSecurityClearance = knowledgeItemSecurityClearance;
    }
    
    @Column(name="Knowledge_Item_Source", length=20)
    public String getKnowledgeItemSource() {
        return this.knowledgeItemSource;
    }
    
    public void setKnowledgeItemSource(String knowledgeItemSource) {
        this.knowledgeItemSource = knowledgeItemSource;
    }
    
    @Column(name="Knowledge_Item_Type", length=100)
    public String getKnowledgeItemType() {
        return this.knowledgeItemType;
    }
    
    public void setKnowledgeItemType(String knowledgeItemType) {
        this.knowledgeItemType = knowledgeItemType;
    }
    
    @Column(name="Subject_Domain", length=100)
    public String getSubjectDomain() {
        return this.subjectDomain;
    }
    
    public void setSubjectDomain(String subjectDomain) {
        this.subjectDomain = subjectDomain;
    }




}


